"use client";

import { useState } from "react";
import { toast } from "sonner";
import { ArrowDown, ArrowUp, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useInventory } from "@/context/InventoryContext";
import { TRANSACTION_TYPE_LABELS } from "@/lib/inventory-utils";
import { cn } from "@/lib/utils";
import type {
  AdjustmentDirection,
  InventoryRow,
  InventoryTransactionType,
} from "@/types";

interface StockAdjustmentDialogProps {
  row: InventoryRow | null;
  onOpenChange: (open: boolean) => void;
}

/**
 * Which movement types a human may record by hand.
 *
 * SALE_POS, SALE_ONLINE and PURCHASE are deliberately absent: those must
 * be generated by the sale or purchase that caused them, carrying that
 * document's reference. Letting someone hand-key a "POS Sale" would
 * produce a ledger row that points at no invoice - an unexplained
 * movement wearing an explanation's clothing.
 */
const MANUAL_TYPES: InventoryTransactionType[] = [
  "ADJUSTMENT",
  "DAMAGE",
  "RETURN",
  "TRANSFER",
];

/** Reasons a shop actually gives. Free text stays available. */
const REASON_PRESETS = [
  "Stock count correction",
  "Damaged item",
  "Missing item",
  "Initial correction",
  "Returned to stock",
  "Other",
];

export function StockAdjustmentDialog({
  row,
  onOpenChange,
}: StockAdjustmentDialogProps) {
  const { adjustStock } = useInventory();

  const [direction, setDirection] = useState<AdjustmentDirection>("decrease");
  const [quantity, setQuantity] = useState(1);
  const [type, setType] = useState<InventoryTransactionType>("ADJUSTMENT");
  const [preset, setPreset] = useState(REASON_PRESETS[0]);
  const [note, setNote] = useState("");
  const [error, setError] = useState<string | null>(null);

  if (!row) return null;

  const signed = direction === "decrease" ? -quantity : quantity;
  const projectedStock = row.stock + signed;
  const wouldGoNegative = projectedStock < 0;
  const quantityInvalid = !Number.isFinite(quantity) || quantity <= 0;

  // "Other" means the note IS the reason, so it becomes required.
  const reason = preset === "Other" ? note.trim() : preset;
  const reasonMissing = !reason;

  function reset() {
    setDirection("decrease");
    setQuantity(1);
    setType("ADJUSTMENT");
    setPreset(REASON_PRESETS[0]);
    setNote("");
    setError(null);
  }

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!row) return;

    const result = adjustStock({
      productId: row.productId,
      direction,
      quantity,
      // The note is appended so the free-text detail survives alongside
      // the preset - a ledger entry saying only "Damaged item" is less
      // useful in six months than one that says which unit and how.
      reason: note.trim() && preset !== "Other" ? `${preset} - ${note.trim()}` : reason,
      type,
    });

    if (!result.ok) {
      setError(result.error);
      return;
    }

    toast.success("Stock adjusted.", {
      description: `${row.name}: ${row.stock} → ${result.newStock}`,
    });
    reset();
    onOpenChange(false);
  }

  return (
    <Dialog open={Boolean(row)} onOpenChange={(open) => { if (!open) reset(); onOpenChange(open); }}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Adjust Stock</DialogTitle>
          <DialogDescription className="truncate">
            {row.name} &middot;{" "}
            <span className="font-mono text-xs">{row.sku}</span>
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} noValidate className="space-y-4">
          {/* --- Direction --- */}
          <fieldset>
            <legend className="mb-1.5 text-sm font-medium text-foreground">
              Adjustment Type
            </legend>
            <div className="grid grid-cols-2 gap-2">
              {(["increase", "decrease"] as AdjustmentDirection[]).map((dir) => {
                const active = direction === dir;
                const Icon = dir === "increase" ? ArrowUp : ArrowDown;
                return (
                  <label
                    key={dir}
                    className={cn(
                      "flex cursor-pointer items-center justify-center gap-2 rounded-lg border-2 py-2.5 text-sm font-medium capitalize transition-colors",
                      active
                        ? dir === "increase"
                          ? "border-success bg-success/10 text-success"
                          : "border-destructive bg-destructive/10 text-destructive"
                        : "border-border text-muted-foreground hover:border-secondary/40"
                    )}
                  >
                    <input
                      type="radio"
                      name="direction"
                      value={dir}
                      checked={active}
                      onChange={() => { setDirection(dir); setError(null); }}
                      className="sr-only"
                    />
                    <Icon className="size-4" aria-hidden="true" />
                    {dir}
                  </label>
                );
              })}
            </div>
          </fieldset>

          {/* --- Quantity + movement type --- */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label
                htmlFor="adj-qty"
                className="mb-1 block text-sm font-medium text-foreground"
              >
                Quantity
              </label>
              <input
                id="adj-qty"
                type="number"
                min={1}
                step={1}
                inputMode="numeric"
                value={quantity === 0 ? "" : quantity}
                onChange={(e) => {
                  setQuantity(Math.floor(Number(e.target.value)) || 0);
                  setError(null);
                }}
                className={cn(
                  "h-10 w-full rounded-lg border bg-background px-3 text-sm tabular-nums outline-none transition-colors",
                  quantityInvalid || wouldGoNegative
                    ? "border-destructive focus:ring-2 focus:ring-destructive/25"
                    : "border-border focus:border-secondary focus:ring-2 focus:ring-ring/30"
                )}
              />
            </div>

            <div>
              <label
                htmlFor="adj-type"
                className="mb-1 block text-sm font-medium text-foreground"
              >
                Record as
              </label>
              <Select
                value={type}
                onValueChange={(v) => setType(v as InventoryTransactionType)}
              >
                <SelectTrigger id="adj-type" className="h-10 w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {MANUAL_TYPES.map((t) => (
                    <SelectItem key={t} value={t}>
                      {TRANSACTION_TYPE_LABELS[t]}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* --- Reason --- */}
          <div>
            <label
              htmlFor="adj-reason"
              className="mb-1 block text-sm font-medium text-foreground"
            >
              Reason <span className="text-destructive">*</span>
            </label>
            <Select value={preset} onValueChange={(v) => { setPreset(v); setError(null); }}>
              <SelectTrigger id="adj-reason" className="h-10 w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {REASON_PRESETS.map((r) => (
                  <SelectItem key={r} value={r}>
                    {r}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            <textarea
              value={note}
              onChange={(e) => { setNote(e.target.value); setError(null); }}
              rows={2}
              placeholder={
                preset === "Other"
                  ? "Describe the reason (required)"
                  : "Extra detail (optional)"
              }
              aria-label="Adjustment note"
              className={cn(
                "mt-2 w-full resize-y rounded-lg border bg-background px-3 py-2 text-sm outline-none transition-colors placeholder:text-muted-foreground",
                preset === "Other" && reasonMissing
                  ? "border-destructive focus:ring-2 focus:ring-destructive/25"
                  : "border-border focus:border-secondary focus:ring-2 focus:ring-ring/30"
              )}
            />
          </div>

          {/* --- Live preview: the whole point of the dialog --- */}
          <div className="grid grid-cols-3 items-center gap-2 rounded-lg border border-border bg-muted/40 p-3 text-center">
            <div>
              <p className="text-[11px] text-muted-foreground">Current</p>
              <p className="font-heading text-lg font-bold tabular-nums text-foreground">
                {row.stock}
              </p>
            </div>
            <div>
              <p className="text-[11px] text-muted-foreground">Adjustment</p>
              <p
                className={cn(
                  "font-heading text-lg font-bold tabular-nums",
                  direction === "increase" ? "text-success" : "text-destructive"
                )}
              >
                {quantityInvalid ? "-" : signed > 0 ? `+${signed}` : signed}
              </p>
            </div>
            <div>
              <p className="text-[11px] text-muted-foreground">New Stock</p>
              <p
                className={cn(
                  "font-heading text-lg font-bold tabular-nums",
                  wouldGoNegative ? "text-destructive" : "text-primary"
                )}
              >
                {quantityInvalid ? "-" : projectedStock}
              </p>
            </div>
          </div>

          {(error || wouldGoNegative) && (
            <p
              role="alert"
              className="flex items-start gap-1.5 rounded-md bg-destructive/10 p-2.5 text-xs font-medium text-destructive"
            >
              <AlertCircle className="mt-px size-3.5 shrink-0" aria-hidden="true" />
              {error ??
                `Insufficient stock. Only ${row.stock} ${
                  row.stock === 1 ? "unit is" : "units are"
                } available.`}
            </p>
          )}

          <p className="rounded-md bg-muted/60 p-2.5 text-[11px] leading-relaxed text-muted-foreground">
            This writes an inventory transaction recording the before and after
            figures. Demo only - it is stored in this browser and does not reach
            the storefront or a database.
          </p>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => { reset(); onOpenChange(false); }}
              className="h-10"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={quantityInvalid || wouldGoNegative || reasonMissing}
              className="h-10 bg-accent font-semibold text-accent-foreground hover:bg-gold-deep"
            >
              Save Adjustment
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
