/**
 * Inventory domain types.
 *
 * THE CENTRAL IDEA
 * ----------------
 * A product's `stock` number is a CACHE. The inventory transaction ledger
 * is the truth.
 *
 *     stock  =  sum of every transaction's quantity, ever
 *
 * Keeping both looks redundant and is not. Without the cached number,
 * showing a stock figure on the storefront would mean summing a ledger
 * that grows forever. Without the ledger, a stock figure is an assertion
 * nobody can check - "we have 8" with no way to answer "why 8?".
 *
 * Shops lose money in exactly that gap. When the shelf says 6 and the
 * system says 8, the ledger is what tells you whether two walked out, two
 * were damaged and never recorded, or a purchase was entered twice.
 */

/**
 * Every reason stock can move.
 *
 * A union, not `string`, so a typo like "SALE_ONLNE" is a compile error
 * rather than a transaction that silently matches no filter and no report.
 */
export type InventoryTransactionType =
  /** Stock as it stood when the product was first entered. */
  | "INITIAL_STOCK"
  /** Goods received from a supplier. Generated by /admin/purchases later. */
  | "PURCHASE"
  /** Sold through the website. */
  | "SALE_ONLINE"
  /** Sold at the counter. */
  | "SALE_POS"
  /** Customer brought it back; it is sellable again. */
  | "RETURN"
  /** Broken, water-damaged, unsellable. Leaves stock, never to return. */
  | "DAMAGE"
  /** A human corrected the number: stock count, shrinkage, data fix. */
  | "ADJUSTMENT"
  /** Moved between locations. One shop today; branches later. */
  | "TRANSFER";

/**
 * One movement.
 *
 * SIGNED QUANTITY (Option A from the brief).
 * `quantity` is negative for anything leaving and positive for anything
 * arriving, so this invariant holds on every single row:
 *
 *     previousStock + quantity === newStock
 *
 * That is the whole reason for the choice. The ledger checks itself: any
 * row where the arithmetic fails is corrupt, and a script can find it in
 * one pass. With unsigned quantities you would have to consult a separate
 * table of "which types subtract", and the day someone adds a new type
 * without updating that table, the ledger silently drifts.
 *
 * The cost is that the UI must never show a bare "-2" without its type -
 * see the transaction table, which always shows both.
 */
export interface InventoryTransaction {
  id: string;
  /** Links to Product.id. The relationship that makes this a ledger. */
  productId: string;
  /** Denormalised so history stays readable after a product is renamed. */
  productName: string;
  productSku: string;

  type: InventoryTransactionType;

  /** Signed. Negative = stock left, positive = stock arrived. Never 0. */
  quantity: number;

  /** Stock immediately before this movement. */
  previousStock: number;
  /** Stock immediately after. Always previousStock + quantity. */
  newStock: number;

  /**
   * What caused it: an invoice number, a purchase order, a return note.
   * This is what turns "stock went down by 2" into "stock went down by 2
   * BECAUSE of invoice SM-INV-0008".
   */
  referenceId?: string;

  /** Free text - required for manual adjustments, optional elsewhere. */
  note?: string;

  /** Who did it. Generic role names until staff accounts exist. */
  createdBy: string;

  /** ISO 8601. Becomes a Firestore Timestamp later. */
  createdAt: string;
}

/**
 * The three buckets the inventory page filters by.
 *
 * DELIBERATELY SEPARATE from `StockLevel` in types/admin.ts, which adds a
 * "critical" tier for the dashboard's low-stock widget. Both are derived
 * from the SAME thresholds by the same file (lib/stock.ts) - this is the
 * coarse view for filtering, that is the fine view for alerting. Neither
 * re-implements the comparison.
 */
export type StockStatus = "in-stock" | "low-stock" | "out-of-stock";

/** Which direction a manual adjustment moves stock. */
export type AdjustmentDirection = "increase" | "decrease";

/** What the adjustment dialog collects. */
export interface StockAdjustmentInput {
  productId: string;
  direction: AdjustmentDirection;
  /** Always positive here; the direction decides the sign. */
  quantity: number;
  /** Required. An adjustment with no reason is an unexplained hole. */
  reason: string;
  /** Lets one dialog record DAMAGE and RETURN as well as ADJUSTMENT. */
  type: InventoryTransactionType;
}

/** A product plus everything the inventory screens need about it. */
export interface InventoryRow {
  productId: string;
  name: string;
  sku: string;
  brand: string;
  categoryName: string;
  categorySlug: string;
  image: string | null;
  /** Live stock: the seed value plus every local movement. */
  stock: number;
  lowStockThreshold: number;
  status: StockStatus;
  /** Selling price - shown for context, NOT used for valuation. */
  price: number;
  /** ISO of the most recent movement, or the product's creation date. */
  lastUpdated: string;
  /** Product lifecycle - NOT the same thing as stock status. */
  productStatus: "active" | "draft" | "archived";
}

/** Totals for the summary cards. */
export interface InventorySummary {
  totalProducts: number;
  /** Sum of stock across every product. */
  totalUnits: number;
  lowStockCount: number;
  outOfStockCount: number;
  /**
   * Stock valued at what it COST, not what it sells for.
   *
   * Cost, because that is the money currently tied up in the shelves.
   * Valuing inventory at selling price would book profit that has not
   * happened yet - the goods have not sold, and some never will.
   */
  costValue: number;
}
